name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Package
        shell: bash
        run: |
          mkdir dist
          
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp target/release/RMCPT.exe dist/
          else
            cp target/release/RMCPT dist/
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RMCPT-${{ runner.os }}
          path: dist/


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/**/*
